### ISSUE TITLE
tracking script - lost Perseus document ids?

### ISSUE THREAD

**Issue by balmas** [PerseusDL/tei-conversion-tools#13]
Hi @srdee -- was the dropping of the Perseus document ids from the tracking output intentional? I think we'd like it to be added back in.

Thanks!

**Comment by srdee** [comment]
@balmas yes it was! And they weren't dropped--this draft was generated only from the files currently in the repos! My next step will be to incorporate the information from the P4 to P5 spreadsheet, including the document IDs, and then enable information to be drawn from classics.xml as well.

**Comment by srdee** [comment]
Reopening because I'll just close when the P4 to P5 part of the script is committed

**Comment by srdee** [comment]
P4 to P5 info is now incorporated with https://github.com/PerseusDL/canonical-latinLit/commit/c85b1ed8608b3ec3dddf8e776c6d85bf831cbe4b , 
https://github.com/PerseusDL/canonical-greekLit/commit/330b20f32d8e88162dacdfb0c8c6308a7085c84b
and https://github.com/PerseusDL/tei-conversion-tools/commit/2037ee87baf61beceb75ca599d0c7d04af8b9dcc

**Comment by balmas** [comment]
super!
