### ISSUE TITLE
Write usage notes for milestones_to_divs.xsl

### ISSUE THREAD

**Issue by srdee** [PerseusDL/tei-conversion-tools#20]
@balmas would you mind sketching notes on adapting the current version milestones_to_divs.xsl to work with various texts out [here](https://github.com/PerseusDL/tei-conversion-tools/wiki/Milestones-to-Divs)? I lost the notes I took in a text file from the Hangout in fall '13--sorry!!! No need to get into great detail--as long as I can follow the notes I'm happy to flesh them out.

**Comment by balmas** [comment]
yes will try to do this first thing tomorrow

**Comment by balmas** [comment]
okay @srdee I added some notes. let me know if you need anything more on this.

**Comment by srdee** [comment]
nope--looks fantastic!
