### ISSUE TITLE
speaker to said code--missing?

### ISSUE THREAD

**Issue by srdee** [PerseusDL/tei-conversion-tools#22]
@balmas didn't you have an xsl or something to do speaker to said conversions? If so, could you please add it to the repo and write brief notes on it here: https://github.com/PerseusDL/tei-conversion-tools/wiki/Speaker-to-Said   ?

...if not, would you mind just writing your most current thoughts on the issue here: https://github.com/PerseusDL/tei-conversion-tools/wiki/Speaker-to-Said  ?

**Comment by balmas** [comment]
wiki updated too.

**Comment by srdee** [comment]
Awesome! Thanks a million!
