### ISSUE TITLE
cannot install tracking tools (OS X 10.6.8)

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/tei-conversion-tools#34]
Instructions here:
https://github.com/PerseusDL/tei-conversion-tools/wiki/Tracking-Data
result in the same error after I install homebrew and try to install jing or parallel:

> brew install jing
> Error: No such file or directory - /usr/bin/xcode-select

looks like there is something about the dir where xcode is. I've confirmed that I have it, but it's not in /usr/bin where it is expected to be. I attempted to perform a custom install of xcode via the OS X installer disk, according to instructions, but this failed.

I will follow up if I can figure out another workaround.

**Comment by fbaumgardt** [comment]
```
sudo ln -s `which xcode-select` /usr/bin/xcode-select
```

should remove the symptom, but it's still ominous that your xcode-select isn't in /usr/bin/.

**Comment by lcerrato** [comment]
Still not working.
Going to try to install 3.2.6 per instructions.
brew doctor indicates it's still not where it is expected to be.

**Comment by lcerrato** [comment]
More info. This is in response to user pull request

https://github.com/PerseusDL/canonical-greekLit/pull/24

I am unclear as to how the tracking figures into this and am trying to figure out that workflow. It appears the end user who has made the merge pull request should be running the script, yes?

(I also want to be able to run it obviously but since this is a problem, I'd like to refocus on the pull request at hand).

**Comment by lcerrato** [comment]
did an uninstall, reinstall of x-code and got it working, will open new issue about point above
