### ISSUE TITLE
generic_div.xsl transformation

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/tei-conversion-tools#43]
I have applied entities.xslt and then tried generic_div.xsl

This deleted the text body.

**Comment by TDBuck** [comment]
I also just tried generic_div.xsl and had it eat the text body.

**Comment by balmas** [comment]
Hi guys sorry I apparently broke it in my hurried attempts to make it better -- I just pushed a fix to it -- hopefully it's working better now.

**Comment by lcerrato** [comment]
Thanks! I'll close this when we have a chance to test it.

**Comment by lcerrato** [comment]
Have the new version and it doesn't make any changes to the file I'm working on. Is this supposed to take care of the cRefPattern?

**Comment by balmas** [comment]
have you already added the tei namespace to your file? this xslt was setup to run before the namespace is added

**Comment by lcerrato** [comment]
No, I don't think I had. Only converted entities. But I will check that next file and update this thread with more useful and complete info.

**Comment by lcerrato** [comment]
Update: my file apparently was partially edited already. I tried to run this on a cleaner file and got different results, so I think it's definitely fixed.
