### ISSUE TITLE
quotes question

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/tei-conversion-tools#49]
Am I correct in thinking this is still not CTS compliant for a line based work?
`<q>`
                        `<l n="37">...</l>`
                        `<l n="38">...</l>`
                        `<l n="39">...</l>`
                        `<l n="40">...</l>`
                      `<l n="41">...</l>`
                        `<l n="42">...</l>`
                   `</q>`

**Comment by balmas** [comment]
I'm pretty sure that's true, because it will break on range requests, e.g. if you requested lines 36-39. @PonteIneptique do you agree?

**Comment by PonteIneptique** [comment]
It does not anymore. There is no issue with this anymore (Normally.)

**Comment by lcerrato** [comment]
No, it does not break the display, but are the quotes supposed be contained within the default hierarchy or not?

**Comment by PonteIneptique** [comment]
I am not sure I get the question (language barrier most probably). Could you translate it into code ? :D

**Comment by gregorycrane** [comment]
the alternate model would be this -- much more cumbersome.

`<l n="37"><q>...</q></l>`
`<l n="38"><q>...</q></l>`
`<l n="39"><q>...</q></l>`

**Comment by lcerrato** [comment]
This issue: https://github.com/PerseusDL/tei-conversion-tools/wiki/Quotes,-Opening-and-Closing
`We need to solve this problem for quotes that cross the hierarchy`

The quote open and close is crossing the default CTS hierarchy.

Say  we have a quote, and the default hierarchy breaks this way, where 1 and 2 are sections or lines or whatever your default is:
`[1]"Let me not find you, old man, by the hollow ships, either tarrying now or coming back later, lest your staff and the wreath of the god not protect you. [2]Her I will not set free."`

how should this be made cts compliant?

Currently, it would look like this:
`<div ...><p><quote>Let me not find you, old man, by the hollow ships, either tarrying now or coming back later, lest your staff and the wreath of the god not protect you. </p></div><div ...><p>Her I will not set free.</quote></p></div>`

but the above instructions indicate it should look like this:
`<div ...><p><quote>Let me not find you, old man, by the hollow ships, either tarrying now or coming back later, lest your staff and the wreath of the god not protect you.</quote></p></div><div ...><p><quote rend="merge">Her I will not set free.</quote></p></div>`

**Comment by gregorycrane** [comment]
i lost my angle brackets and tags

L Q Q L
L Q Q L etc.

**Comment by PonteIneptique** [comment]
When quotes crosses (Or any other tag really) crosses CTS tags, the general accepted solution is indeed to use merge. In the original question at the top, you had no crossing tags, which made it unclear to me. so indead, you could have either : 

`<div ...><p><quote>Let me not find you, old man, by the hollow ships, either tarrying now or coming back later, lest your staff and the wreath of the god not protect you.</quote></p></div><div ...><p><quote rend="merge">Her I will not set free.</quote></p></div>` or actually quote outside the p if it's TEI compliant.

@gregorycrane : To show code in github comment, use `

**Comment by PonteIneptique** [comment]
Another example with line : 

`````` xml
<div>
<q>
<l n="37">...</l>
<l n="38">...</l>
<l n="39">...</l>
</q>
<div>
<div>
<q rend="merge">
<l n="40">...</l>
<l n="41">...</l>
<l n="42">...</l>
</q>```
``````

**Comment by PonteIneptique** [comment]
If this answer the question, feel free to close it :)

**Comment by lcerrato** [comment]
Thanks! @PonteIneptique  
The instructions are not clear for poetry versus prose. I would have enclosed the quote tags within the line tags to be safe. :)
